2025-05-09 17:05:15,403 - INFO - Received request at /run endpoint
2025-05-09 17:05:15,404 - INFO - Authorization successful.
2025-05-09 17:05:15,404 - INFO - Data to process: {'name': 'Test User', 'email': 'test@example.com', 'phone': '+380961234567'}
2025-05-09 17:05:15,404 - WARNING - ALERT triggered: email and phone — report saved.
2025-05-09 17:05:15,426 - ERROR - Failed to contact Business service: HTTPConnectionPool(host='localhost', port=8001): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106de2200>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-05-09 22:01:52,027 - INFO - Received request at /run endpoint
2025-05-09 22:01:52,033 - INFO - Successful authorization.
2025-05-09 22:01:52,033 - INFO - Data to process: {'name': 'Test User', 'email': 'test@example.com', 'phone': '+380961234567'}
2025-05-09 22:01:52,034 - WARNING - ALERT triggered: email and phone — report saved.
2025-05-09 22:01:52,048 - ERROR - Unable to contact Business service: HTTPConnectionPool(host='localhost', port=8001): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10324e200>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-05-09 22:03:38,624 - INFO - Received request at /run endpoint
2025-05-09 22:03:38,625 - INFO - Successful authorization.
2025-05-09 22:03:38,625 - INFO - Data to process: {'name': 'Anastasiia Plaskonis', 'email': 'plaskonis.pn@ucu.edu.ua', 'phone': '+3801234567'}
2025-05-09 22:03:38,626 - WARNING - ALERT triggered: email — report saved.
2025-05-09 22:03:38,633 - ERROR - Unable to contact Business service: HTTPConnectionPool(host='localhost', port=8001): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1047122c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-05-09 22:51:32,579 - INFO - Received request at /run endpoint
2025-05-09 22:51:32,580 - INFO - Successful authorization.
2025-05-09 22:51:32,580 - INFO - Data to process: {'name': 'Anastasiia Plaskonis', 'email': 'plaskonis.pn@ucu.edu.ua', 'phone': '+3801234567'}
2025-05-09 22:51:32,580 - WARNING - ALERT triggered: email — report saved.
2025-05-09 22:51:32,644 - INFO - Processed data: {'processed': True, 'original': {'name': 'Anastasiia Plaskonis', 'email': 'plaskonis.pn@ucu.edu.ua', 'phone': '+3801234567'}}
2025-05-09 22:51:32,652 - ERROR - Unable to save data to DB: HTTPConnectionPool(host='localhost', port=8002): Max retries exceeded with url: /save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107b0baf0>: Failed to establish a new connection: [Errno 61] Connection refused'))
